<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{  //web
    public function index()
    {
        $students = Student::orderBy('total_marks', 'desc')->get();
        return view('students.index', compact('students'));
        $students = Student::all();
    }
 //api
     public function allstudent()
    {
        $students = Student::orderBy('total_marks', 'desc')->get();
        $students = Student::all();
        return response()->json($students);
    }


    public function create()
    {
        return view('students.create');
    }
        //web
  public function store(Request $request)
    {
        $request->validate([
            'student_name' => 'required|string|max:255',
            'student_email' => 'required|email|unique:students',
            'student_phone' => 'nullable|string|max:20',
            'total_marks' => 'required|integer|min:0|max:500',
        ]);

        $student = Student::create($request->all());
        
        // Auto-assign rank based on marks
        $rank = match(true) {
            $student->total_marks >= 400 => 'First Class',
            $student->total_marks >= 300 => 'Second Class',
            $student->total_marks >= 200 => 'Third Class',
            default => 'Fail'
        };
        
        $student->update(['rank' => $rank]);

        return redirect()->route('students.index')->with('success', 'Student added successfully!');
    }
//api
public function studentstore(Request $request)
{
    // ✅ Step 1: Validate input before saving
    $request->validate([
        'student_name'  => 'required|string|max:255',
        'student_email' => 'required|email|unique:students,student_email',
        'student_phone' => 'nullable|string|max:20',
        'total_marks'   => 'required|integer|min:0|max:500',
    ]);

    // ✅ Step 2: Create student record
    $student = Student::create([
        'student_name'  => $request->student_name,
        'student_email' => $request->student_email,
        'student_phone' => $request->student_phone,
        'total_marks'   => $request->total_marks,
    ]);

    // ✅ Step 3: Auto-assign rank based on total marks
    $rank = match (true) {
        $student->total_marks >= 400 => 'First Class',
        $student->total_marks >= 300 => 'Second Class',
        $student->total_marks >= 200 => 'Third Class',
        default => 'Fail',
    };

    // ✅ Step 4: Update student with rank
    $student->update(['rank' => $rank]);

    // ✅ Step 5: Return JSON response (with autogenerated ID)
     return response()->json($student);
}

//web
    public function show($id)
{
    $student = Student::find($id);
    $student->created_at = $student->created_at->format('Y-m-d H:i:s');
    $student->updated_at = $student->updated_at->format('Y-m-d H:i:s');
 
    if (!$student) {
        return response()->json(['error' => 'Student not found'], 404);
    }
     return view('students.show', compact('student'));
     
}
 //api
public function showstudent($id)
{
    $student = Student::find($id);
    $student->created_at = $student->created_at->format('Y-m-d H:i:s');
    $student->updated_at = $student->updated_at->format('Y-m-d H:i:s');
 
    if (!$student) {
        return response()->json(['error' => 'Student not found'], 404);
    }
   //  return view('students.show', compact('student'));
       return response()->json($student);
}
 
   public function edit(Student $student)
    {
        return view('students.edit', compact('student'));
    }
   //web
    public function update(Request $request, Student $student)
    {
        $request->validate([
            'student_name' => 'required|string|max:255',
            'student_email' => 'required|email|unique:students,student_email,' . $student->id,
            'student_phone' => 'nullable|string|max:20',
            'total_marks' => 'required|integer|min:0|max:500',
        ]);

        $student->update($request->all());
        
        // Auto-assign rank based on marks
        $rank = match(true) {
            $student->total_marks >= 400 => 'First Class',
            $student->total_marks >= 300 => 'Second Class',
            $student->total_marks >= 200 => 'Third Class',
            default => 'Fail'
        };
        
        $student->update(['rank' => $rank]);

        return redirect()->route('students.index')->with('success', 'Student updated successfully!');
    }
    //api
 public function studentupdate(Request $request, $id)
{
    // ✅ Find the student
    $student = Student::find($id);

    // ✅ Validate input
    $request->validate([
        'student_name'  => 'sometimes|required|string|max:255',
        'student_email' => 'sometimes|required|email|unique:students,student_email,' . $id,
        'student_phone' => 'nullable|string|max:20',
        'total_marks'   => 'sometimes|required|integer|min:0|max:500',
    ]);

    // ✅ Update student fields
    $student->update([
        'student_name'  => $request->student_name ?? $student->student_name,
        'student_email' => $request->student_email ?? $student->student_email,
        'student_phone' => $request->student_phone ?? $student->student_phone,
        'total_marks'   => $request->total_marks ?? $student->total_marks,
    ]);

    // ✅ Recalculate rank if total_marks changed
    $rank = match (true) {
        $student->total_marks >= 400 => 'First Class',
        $student->total_marks >= 300 => 'Second Class',
        $student->total_marks >= 200 => 'Third Class',
        default => 'Fail',
    };

    $student->update(['rank' => $rank]);

    // ✅ Return response
     return response()->json($student);
  
}
//web
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index')->with('success', 'Student deleted successfully!');
    }

//api
public function studentdelete($id)
{
    $student = Student::find($id);
    // Delete the record
    $student->delete();

    // Return success message
   return response()->json([
        'message' => 'Student deleted successfully'
   ]);
}


}
